apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: deploy_name
  labels:
    app: deploy_name
spec:
  replicas: 1
  selector: # define how the deployment finds the pods it mangages
    matchLabels:
      app: deploy_name
  template: # define the pods specifications
    metadata:
      labels:
        app: deploy_name
        appointedge: false
        needgpu: false
    spec:
      containers:
      - name: binpack-1
        image: cheyang/gpu-player:v2
        resources:
          limits:
            # GiB
            cpu: 100m
            memory: 200Mi
            aliyun.com/gpu-mem: 2000
          requests:
            cpu: 100m
            memory: 200Mi
            aliyun.com/gpu-mem: 2000
      schedulerName: myscheduler

